name: Build & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  install-and-build:
    name: 🛠️ Install & Build
    runs-on: ubuntu-latest

    steps:
      - name: 🗜️ Checkout
        uses: actions/checkout@v4

      - name: 🗜️ Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: 🛠️ Install
        uses: ./.github/actions/cached-deps

      - name: 📦 Build
        run: yarn build

      - name: 🚀 Publish NPM
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: 🚀 Publish NPM BETA
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == true
        run: cd dist && npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: 🛠️ Set up package for GPR
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
        run: yarn script:gpr-setup

      - name: 🛠️ Use GPR
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/
          scope: '@celtian'

      - name: 🚀 Publish to GitHub Package Registry
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
        run: |
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
